#前端访问端口
server:
  port: 7777
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    host: 43.143.191.79         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password:               # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 200       # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10          # 连接池中的最大空闲连接
        max-wait: -1          # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0           # 连接池中的最小空闲连接
    timeout: 1000
  datasource:
    url: jdbc:mysql://localhost:3306/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #逻辑删除字段，与数据库中的 del_flag相对于
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      #主键自增
      id-type: auto
oss:
  accessKey: q9zosL7l6aU1pJxsJSeRCVc_rLVg5tqkxE33q8MX
  secretKey: koA2z2MFjGq4RjCZQqh6N7gLzWcyjPh6vVzJAKwc
  bucket: ikun-blog